let data=null;
const $=id=>document.getElementById(id);
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function flatten(comments,out=[]){for(const c of comments||[]){out.push(c);flatten(c.replies,out)}return out}
function commentHTML(c){return `<div class="comment"><div class="comment-meta"><b>${esc(c.author||'[deleted]')}</b> · ${c.score??0} points · ${c.created_utc?new Date(c.created_utc*1000).toLocaleString():''}</div><div class="comment-text">${esc(c.body||'[deleted]')}</div>${(c.replies||[]).map(commentHTML).join('')}</div>`}
async function extract(){const url=$('url').value.trim();$('status').textContent='Extracting…';$('status').className='';$('extract').disabled=true;$('post').innerHTML='';$('comments').innerHTML='';$('actions').hidden=true;try{const api=`https://www.reddit.com/oembed?url=${encodeURIComponent(url)}&format=json`;const r=await fetch(api);if(!r.ok)throw Error('Reddit did not accept this URL.');const o=await r.json();data={source_url:url,oembed:o,post:null,comments:[]};$('post').innerHTML=`<div class="card"><h2>${esc(o.title||'Reddit post')}</h2><div class="meta">${esc(o.author_name||'')} · ${esc(o.provider_name||'Reddit')}</div><p class="meta">The public oEmbed endpoint does not expose the full post body or comments.</p><p><a href="${esc(url)}" target="_blank" rel="noreferrer">Open Reddit post</a></p></div>`;$('status').textContent='Basic post metadata loaded. Full comments require a Reddit API/backend connection.';$('actions').hidden=false}catch(e){$('status').textContent=e.message;$('status').className='error'}finally{$('extract').disabled=false}}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('extract').onclick=extract;
$('json').onclick=()=>navigator.clipboard.writeText(JSON.stringify(data,null,2));
$('download').onclick=()=>download('reddit-post.json',JSON.stringify(data,null,2),'application/json');
$('csv').onclick=()=>{const rows=[['author','score','created_utc','body']];for(const c of flatten(data.comments))rows.push([c.author,c.score,c.created_utc,c.body]);download('reddit-comments.csv',rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')};
